name: 'AHL Deployment'

on:
  push:
    #paths:
    #- 'ahl/**'
    branches:
    - main
  #pull_request:



jobs:
  terraform:
    name: 'Terraform-deploy'
    runs-on: ubuntu-latest
    environment: dev

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        #working-directory: hockey-ahl
    
    #if: github.ref == 'refs/heads/master'
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TFCLOUD_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      #working-directory: ./terraform
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    #- name: Terraform Format
    #  #working-directory: ./terraform
    #  run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      #working-directory: ./terraform
      run: terraform plan -var-file=".github\workflows\hockey-ahl\hockey-ahl.tfvars"
      #with:
      #  var_file: |
      #    hockey-ahl\hockey-ahl.tfvars

    # Auto Apply
    - name: Terraform Apply
      #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve